version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-cicd
    ports:
      - "8080:8080"  # Jenkins UI
      - "50000:50000"  # Jenkins agents
    volumes:
      - jenkins_data:/var/jenkins_home
    restart: unless-stopped
    networks:
      - jenkins-net

  nginx-config:
    image: alpine:latest
    volumes:
      - ./nginx-jenkins.conf:/nginx-jenkins.conf:ro
      - /etc/nginx/sites-available:/sites-available
      - /etc/nginx/sites-enabled:/sites-enabled
    command: >
      sh -c "cp -f /nginx-jenkins.conf /sites-available/jenkins.serp24.online &&
             ln -sf /sites-available/jenkins.serp24.online /sites-enabled/jenkins.serp24.online &&
             ls -l /sites-enabled/jenkins.serp24.online &&
             nginx -t || echo 'NGINX test failed' &&
             systemctl restart nginx || echo 'NGINX restart failed (likely not running on host)'"

volumes:
  jenkins_data:

networks:
  jenkins-net: