version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-cicd
    ports:
      - "8080:8080"  # Jenkins UI
      - "50000:50000"  # Jenkins agents
    volumes:
      - jenkins_data:/var/jenkins_home
    restart: unless-stopped
  nginx-config:
    image: alpine:latest
    volumes:
      - ./nginx.conf:/nginx.conf:ro
      - /etc/nginx/sites-available:/sites-available
      - /etc/nginx/sites-enabled:/sites-enabled
    command: >
      sh -c "cp -f /nginx.conf /sites-available/jenkins.serp24.online &&
             ln -sf /etc/nginx/sites-available/jenkins.serp24.online /sites-enabled/jenkins.serp24.online &&
             ls -l /sites-enabled/jenkins.serp24.online &&
             nginx -t && systemctl restart nginx|| echo 'NGINX test failed'"
    # Runs once and exits
volumes:
  jenkins_data: